# -*- coding: utf-8 -*-
"""ifelse

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9GIzJWLrCkeyq3jukAebppVueLa7NIG
"""

# Operators in Python
# (1). Add(+) ===> 5+2 = 7
# (2). Subtraction(-) ===> 4-2 = 2
# (3). Multiplication(*) ===> 3*7 = 21
# (4). Division(/) ===> 5/2 = 2.5
# (5). Floor Division(//) ===> 5//2 ==> 2
# (6). Module(%) ===> For Remainder Calculation ===> 25%10 = 5(Remainder)
# (7). Greater than (>) ====> 5>2
# (8). Less than (<) ===> 3<8
# (9). Equal to (=) ===> for values Assignment ===> a = 5 , b = 'sam'
# (10).Equal Equal to(==) ==> For values comparison ===> 'a'=='b' , 4==5
# (11). Not Equal to(!=) ===> 4!=5
# (12). Greter than or Equal to(>=) ===> 5>=4  , 4>=4
# (13). Less than or Equal to(<=) ===> 4<=4 , 5<=7

5//2

# Conditional Selection in Python
# if
# elif
# else

a = input("Enter your name:")
if(a == "sam"):
  print("yes")
elif(a == "Rahul"):
  print("No")
elif(a =="Jay"):
  print("ok")
else:
  print("Try Again...")

a = int(input("Enter your age:"))
if(0<=a<=20):
  print("child")
elif(21<=a<=50):
  print("young")
elif(51<=a<=90):
  print("old")
else:
  print("Enter your valid age.....")
#### user ==> course ===> select ===> python ==> fees , duration , java ===> feees , duration  ===> others ===> please select a valid course

# Loop in Python

# Index = 0 , Length = 1

# (1). For loop ==> starting_value include and last_value exclude .
# syntax : for i in range(start_value , last_value , step_value):print(i)
# method - 1
for i in range(0,9,3):
  print(i)

# method - 2
a = "sam"
for b in a :
  print(b)

# method - 2
a = "sam"
for i in a :
  print(i , end = " ")

# (2). while loop

# (a). Initialization
# (b). Condition
# (c). Increment or Decrement

# syntax:
# while(condition):
  # condition

# Q.1 Write a program who print from 1 to 3 ?
i = int(input("Enter first  number:"))  ### Initialization
n = int(input("Enter last number:"))
p = int(input("Enter step number:"))

while(i<=n):   ### Condition
  print(i)
  i = i + p    ### Increment

# step-1 (i=1 , n = 3)
while(1<=3):
  print(1)
# i = 1+1 = 2
# step-2 (i = 2 ,n = 3)
while(2<=3):
  print(2)
  # i= 2 + 1 = 3
# step-3 (i = 3 , n = 3)
while(3<=3):
  print(3)
  # i = 3 + 1 = 4
# step-4 (i = 4 , n = 3)
while(4<=3):
  break
# Final Output ===> 1,2,3

# Q.2 Write a program who can add given numbers ?
# i  =1
# n = 3
# output ===> 1+2+3 = 6

# Q.3 Write a program who add number .
# i = 1234
# output ===> 1+2+3+4 = 10

# Q.4 Write a program who can add even numbers and odd numbers separately .
# i = 1234
# output ===>
# even = 2+4 = 6
# odd = 1+3 = 4

i  =1
 n = 3
 print(i+n)

# output ===> 1+2+3+4 = 10
sum=0
i = 1234
for word in str(i):
  n=int(word)
  sum+=n
print(sum)

# Q.4 Write a program who can add even numbers and odd numbers separately .
i = 1234
sum_even=0
sum_odd=0
for digit in str(i):
  n=int(digit)
  if n%2==0:
   sum_even+=n
  else:
    sum_odd+=n

print(sum_even)
print(sum_odd)